### PR TITLE
 [Issue #31] finished implementation for milestone 1

### PR DESCRIPTION
**Pull request by tosinoni**
1.  This PR is already deployed on heroku
2. Still need to write tests for everything that was written

### CODE REVIEW

**Comment by mohameddahrouj** [comment]
Nice, is this ready to be merged?

**Comment by tosinoni** [comment]
@loushiano do you mind helping me fix your controller and model tests? I added new attributes and changed to Jersey's response instead of ResponseEntity. Thanks bro 😄

**Comment by loushiano** [comment]
@tosinoni  of course not man, i can definitely help, but how would this go?would you merge first and then i write the tests or what?

**Comment by tosinoni** [comment]
I cannot merge the PR because the tests are failing now. You can just work on my branch and push your changes/test fix to it. :)

**Pull request merged**
